// <auto-generated />
using System;
using KhalilsOutlet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhalilsOutlet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524183232_SeedProductsTable")]
    partial class SeedProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhalilsOutlet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 5, 24, 11, 32, 32, 151, DateTimeKind.Local).AddTicks(6130),
                            Description = "The Nike V2K Run Sneaker is a blend of nostalgic style and modern performance,ideal for those looking for a sneaker that performs well in both casual and athletic settings.",
                            ImageFileName = "Nike V2k Run Sneaker 1.jpg",
                            Name = "Nike V2k Run Sneaker 1",
                            price = 160m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nike",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 5, 24, 11, 32, 32, 151, DateTimeKind.Local).AddTicks(6186),
                            Description = "The Nike Air Foamposite Pro Forest is a fusion of style and functionality. Its bold design, durable construction,and advanced cushioning make it a favorite among sneaker collectors and athletes..",
                            ImageFileName = "Nike Air Foamposite Pro Forest.jpg",
                            Name = "Nike Air Foamposite Pro Forest",
                            price = 420m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Adidas",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 5, 24, 11, 32, 32, 151, DateTimeKind.Local).AddTicks(6190),
                            Description = "The Adidas Terrex line is highly regarded for its performance and reliability in outdoor settings.",
                            ImageFileName = "Adidas Terrex.jpg",
                            Name = "Adidas Terrex",
                            price = 335m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Adidas",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 5, 24, 11, 32, 32, 151, DateTimeKind.Local).AddTicks(6194),
                            Description = "The Adidas Gazelle Indoor is a blend of classic style and modern functionality. ",
                            ImageFileName = "Adidas Gazelle Indoor.jpg",
                            Name = "Adidas Gazelle Indoor",
                            price = 115m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Reebok",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 5, 24, 11, 32, 32, 151, DateTimeKind.Local).AddTicks(6198),
                            Description = "The Reebok BB4600 is a standout shoe that combines the best of old-school basketball aesthetics with modern comfort and durability.",
                            ImageFileName = "Reebok BB4600.jpg",
                            Name = "Reebok BB4600",
                            price = 225m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
